# SITE CONFIGURATION
baseurl: "" # Set it to "" if use for personal site. The subpath of your site, e.g. /blog/
# url: "http://cyan24.github.io" # the base hostname & protocol for your site
imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"

# Site settings
encoding: utf-8
title: "Cyan的技术笔记"
description: "cyan24的技术笔记, github地址, 前端技术, 讲述前端高效技术与前沿。"
baseurl: "/"  # the subpath of your site, e.g. /blog/
url: "http://cyan24.github.io" # the base hostname & protocol for your site
# cover: "assets/header_image.png"
logo: "assets/logo.png"
keywords: "前后端, cyan, 博客, github, 前端技术, javascript, css, html"
image: "http://ouvens.github.io/blog/assets/logo.png"



# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Cyan的技术笔记
  #avatar: avatar.png
  hometitle: 首页 #display on navigation menu.
  yoursitetitle: Cyan的技术笔记
  gravatar: # Email MD5 hash
  description: "used by search engines" # used by search engines
  visiblewords: 300
  # Header and footer text
  header_text: >
    
  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="https://cyan24.github.io">Cyan的技术笔记</a> 

  # Icons
  rss: false
  email_address: "chianzjcy@aliyun.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "cyan24"
  weibo: 
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest: 
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "cyan24"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  #str_next: "Next"
  #str_prev: "Prev"
  str_continue_reading: "Continue Reading..."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
enforce_ssl: "cyan24.com"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/ 

# Posted in ... with ...
sechby: 
  category:   #in
  tag:   #with

# BUILD SETTINGS
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-paginate